kovengerss/Lawtalk

- WebContent/client_signup/client_signup.html
- WebContent/client_signup/client_sigup.css
> 의뢰인 회원가입 페이지

- WebContent/assets/css/service.css
> 의뢰인 분야 선택하기

- WebContent/LawKnowMainPage.jsp
- WebContent/assets/css/css/mainstyle.css
- WebContent/assets/css/css/rewrite.css
- WebContent/mycounsel.jsp
- WebContent/mypage.jsp
- WebContent/questionLawer.jsp
- WebContent/questionUser.jsp
- WebContent/rewrite.jsp
> 2022/5/23 김건우 프론트 수정본 완성

- WebContent/answer_page.jsp
- WebContent/assets/css/answer_page.css
- WebContent/assets/css/client_request_waiting.css
- WebContent/category2.jsp
- WebContent/category3.jsp
- WebContent/category4.jsp
- WebContent/category5.jsp
- WebContent/category6.jsp
- WebContent/category7.jsp
- WebContent/client_request_waiting.jsp
- WebContent/client_signup.jsp
- WebContent/lawyer_signup.jsp
> 이종임 [회원가입 유효성 검사 추가 / 페이지 연결]

- src/com/lawyer/action/Action.java
- src/com/lawyer/action/ActionInfo.java
> com.lawyer.action

- WebContent/WEB-INF/web.xml
- src/com/lawyer/domain/dao/LawyerDAO.java
- src/com/user/domain/dao/UserDao.java
> dao, web.xml

- WebContent/WEB-INF/web.xml
- WebContent/client_signup.jsp
- WebContent/index.jsp
- WebContent/joinSuccess.jsp
- WebContent/login.jsp
- WebContent/loginSuccess.jsp
- src/com/lawknow/domain/dao/UserDAO.java
- src/com/lawknow/userRegister/UserCheckIdOk.java
- src/com/lawknow/userRegister/UserJoinOk.java
- src/com/lawknow/userRegister/UserLoginFrontController.java
- src/com/lawknow/userRegister/UserLoginOk.java
- src/com/mybatis/config/config.xml
- src/com/mybatis/mapper/UserMapper.xml
> 의뢰인 로그인, 회원가입 백엔드작업

- WebContent/LawjoinSuccess.jsp
- WebContent/LawloginSuccess.jsp
- WebContent/WEB-INF/web.xml
- WebContent/client_signup.jsp
- WebContent/lawyer_signup.jsp
- WebContent/login.jsp
- src/com/lawknow/domain/dao/LawyerDAO.java
- src/com/lawknow/domain/vo/LawyerVO.java
- src/com/lawknow/lawyerRegister/LawyerCheckIdOk.java
- src/com/lawknow/lawyerRegister/LawyerJoinOk.java
- src/com/lawknow/lawyerRegister/LawyerLoginFrontController.java
- src/com/lawknow/lawyerRegister/LawyerLoginOk.java
- src/com/lawknow/userRegister/UserLoginFrontController.java
- src/com/mybatis/mapper/LawyerComment.xml
- src/com/mybatis/mapper/LawyerMapper.xml
> 변호사 로그인 회원가입추가, 오류수정

- WebContent/WEB-INF/web.xml
- WebContent/answer_page.jsp
- WebContent/lawyerCommentSuccess.jsp
- src/com/lawknow/domain/dao/LawyerCommentDAO.java
- src/com/lawknow/domain/vo/LawyerCommentVO.java
- src/com/lawknow/lawyerComment/LawyerCommentFrontController.java
- src/com/lawknow/lawyerComment/LawyerCommentOk.java
- src/com/lawknow/userRegister/UserJoinOk.java
- src/com/mybatis/mapper/LawyerComment.xml
> content 1차

- WebContent/client_signup.jsp
- WebContent/login.jsp
- src/com/lawknow/userRegister/PwChangeOk.java
- src/com/lawknow/userRegister/UserLogin.java
- src/com/lawknow/userRegister/UserLoginFrontController.java
- src/com/lawknow/userRegister/UserLoginOk.java
> 아이디 저장 쿠키 삭제

- src/com/lawknow/lawyerRegister/LawyerLogin.java
- src/com/lawknow/lawyerRegister/LawyerLoginOk.java
- src/com/lawknow/lawyerRegister/LawyerPwChangeOk.java
> 변호사 아이디 저장 쿠키 삭제

- src/com/lawknow/domain/dao/LawyerDAO.java
- src/com/lawknow/domain/dao/UserDAO.java
- src/com/lawknow/lawyerRegister/LawyerLoginOk.java
- src/com/lawknow/userRegister/UserLoginOk.java
- src/com/mybatis/mapper/LawyerMapper.xml
- src/com/mybatis/mapper/UserMapper.xml
> 이름 가져오기 DAO, mapper 추가

- WebContent/pwChange.jsp
- src/com/lawknow/domain/dao/UserDAO.java
- src/com/lawknow/lawyerRegister/LawyerLoginOk.java
- src/com/lawknow/lawyerRegister/LawyerPwChangeOk.java
- src/com/lawknow/userRegister/UserLoginFrontController.java
- src/com/lawknow/userRegister/UserPwCheckOk.java
- src/com/mybatis/mapper/UserMapper.xml
> 비밀번호 변경 ajax추가

- WebContent/mypage.jsp
- WebContent/privacyPage.jsp
- WebContent/test.jsp
- src/com/lawknow/domain/dao/UserDAO.java
- src/com/lawknow/userRegister/UserEmailUpdateOk.java
- src/com/lawknow/userRegister/UserLoginFrontController.java
- src/com/mybatis/mapper/UserMapper.xml
> 회원정보수정 랜덤아이디 추가

- WebContent/assets/js/clientSignUp.js
- WebContent/client_signup.jsp
- WebContent/login.jsp
> 의뢰인 회원가입 유효성 수정,

- WebContent/answer_page.jsp
- src/com/lawknow/domain/dao/FileDAO.java
- src/com/lawknow/domain/dao/LawyerCommentDAO.java
- src/com/lawknow/domain/dao/LawyerDAO.java
- src/com/lawknow/domain/dao/UserDAO.java
- src/com/lawknow/domain/dao/UserReviewDAO.java
- src/com/lawknow/domain/dao/UserWriteDAO.java
- src/com/lawknow/domain/vo/FileVO.java
- src/com/lawknow/domain/vo/LawyerCommentVO.java
- src/com/lawknow/domain/vo/LawyerVO.java
- src/com/lawknow/domain/vo/UserReviewVO.java
- src/com/lawknow/domain/vo/UserVO.java
- src/com/lawknow/domain/vo/UserWriteVO.java
- src/com/lawknow/lawyerComment/LawyerCommentCountOk.java
- src/com/lawknow/lawyerComment/LawyerCommentDeleteOk.java
- src/com/lawknow/lawyerComment/LawyerCommentFrontController.java
- src/com/lawknow/lawyerComment/LawyerCommentOk.java
- src/com/lawknow/lawyerComment/LawyerCommentRequestNumOk.java
- src/com/lawknow/lawyerComment/LawyerCommentUpdateOk.java
- src/com/lawknow/lawyerComment/LawyerCommentViewOk.java
- src/com/lawknow/lawyerComment/LawyerWriteNumOk.java
- src/com/lawknow/lawyerRegister/LawyerCheckIdOk.java
- src/com/lawknow/lawyerRegister/LawyerDeleteAccountOk.java
- src/com/lawknow/lawyerRegister/LawyerEmailUpdateOk.java
- src/com/lawknow/lawyerRegister/LawyerJoinOk.java
- src/com/lawknow/lawyerRegister/LawyerLogin.java
- src/com/lawknow/lawyerRegister/LawyerLoginFrontController.java
- src/com/lawknow/lawyerRegister/LawyerLoginOk.java
- src/com/lawknow/lawyerRegister/LawyerPwChangeOk.java
- src/com/lawknow/lawyerRegister/LawyerPwCheckOk.java
> 살려내라...!!!

- WebContent/assets/css/privacyPage.css
- WebContent/privacyPage.jsp
- src/com/lawknow/domain/dao/UserDAO.java
- src/com/lawknow/userRegister/UserLoginFrontController.java
- src/com/lawknow/userRegister/UserPhonNumUpdateOk.java
- src/com/lawknow/userRegister/UserPhoneNumPushOk.java
- src/com/mybatis/mapper/UserMapper.xml
> 의뢰인 인증번호 발송, 승인 완료

- WebContent/assets/js/lawyerSignUp.js
- WebContent/lawyer_signup.jsp
- src/com/lawknow/domain/dao/LawyerDAO.java
- src/com/lawknow/lawyerRegister/LawyerCheckIdOk.java
- src/com/lawknow/lawyerRegister/LawyerJoinOk.java
- src/com/lawknow/lawyerRegister/LawyerLoginFrontController.java
- src/com/lawknow/lawyerRegister/LawyerLoginOk.java
- src/com/lawknow/userRegister/UserLoginOk.java
> 변호사 회원가입 로그인 오류수정 js수정

- WebContent/compani.jsp
- WebContent/mypage.jsp
- WebContent/privacyPage.jsp
- WebContent/privacyPage2.jsp
- WebContent/pwChange.jsp
- WebContent/pwChange2.jsp
- src/com/lawknow/domain/dao/LawyerDAO.java
- src/com/lawknow/lawyerRegister/LawyerEmailUpdateOk.java
- src/com/lawknow/lawyerRegister/LawyerLoginFrontController.java
- src/com/lawknow/lawyerRegister/LawyerPhonNumUpdateOk.java
- src/com/lawknow/lawyerRegister/LawyerPhoneNumPushOk.java
- src/com/lawknow/userRegister/UserEmailUpdateOk.java
- src/com/lawknow/userRegister/UserLoginFrontController.java
- src/com/lawknow/userWrite/UserWriteCountOk.java
- src/com/mybatis/mapper/LawyerMapper.xml
> 변호사 회원정보수정 인증번호 구현완료

- WebContent/answer_page.jsp
- WebContent/assets/js/comment.js
- src/com/lawknow/domain/vo/LawyerCommentDTO.java
- src/com/lawknow/domain/vo/LawyerCommentVO.java
- src/com/lawknow/lawyerComment/LawyerCommentFrontController.java
- src/com/lawknow/lawyerComment/LawyerCommentListOk.java
- src/com/lawknow/lawyerComment/LawyerCommentOk.java
- src/com/mybatis/mapper/LawyerComment.xml
> 등록 디비 기능 성공

- WebContent/lawlayorMypage.jsp
- WebContent/privacyPage.jsp
- src/com/lawknow/lawyerRegister/LawyerOfficeNameOk.java
- src/com/lawknow/userRegister/UserEmailUpdateOk.java
- src/com/lawknow/userRegister/UserLoginFrontController.java
> 변호사 마이페이지, 이메일 변경 수정 완

- WebContent/answer_page.jsp
- WebContent/assets/js/comment.js
- src/com/lawknow/domain/dao/LawyerCommentDAO.java
- src/com/lawknow/domain/vo/LawyerCommentVO.java
- src/com/lawknow/lawyerComment/LawyerCommentDeleteOk.java
- src/com/lawknow/lawyerComment/LawyerCommentFrontController.java
- src/com/lawknow/lawyerComment/LawyerCommentListOk.java
- src/com/lawknow/lawyerComment/LawyerCommentUpdateOk.java
- src/com/mybatis/config/config.xml
- src/com/mybatis/mapper/LawyerComment.xml
> 댓글 기능 구현 (수정 구현이 오류)

- src/com/lawknow/lawyerRegister/LawyerPwChangeOk.java
> 없어진 파일 다시 추가

- WebContent/clientMypage.jsp
- WebContent/lawlayorMypage.jsp
- src/com/lawknow/domain/dao/UserWriteDAO.java
- src/com/lawknow/lawyerRegister/LawyerPwChangeOk.java
- src/com/lawknow/userRegister/UserMyPageOk.java
- src/com/lawknow/userWrite/UserWriteFrontController.java
- src/com/lawknow/userWrite/UserWriteOk.java
- src/com/mybatis/mapper/UserWrite.xml
> 변호사 마이페이지, 의뢰인 마이페이지 완성

- WebContent/LawKnowMainPage.jsp
- WebContent/LawKnowMainPage2.jsp
- WebContent/client_signup.jsp
- WebContent/login.jsp
- src/com/lawknow/lawyerRegister/LawyerJoinOk.java
- src/com/lawknow/lawyerRegister/LawyerLoginOk.java
> 의뢰인.변호사 로그인 로그아웃 화면구현

- WebContent/LawKnowMainPage.jsp
- WebContent/LawKnowMainPage2.jsp
- WebContent/assets/js/lawyerSignUp.js
- WebContent/lawyer_signup.jsp
> 경로 수정, 변호사 휴대폰 인증 수정

- src/com/lawknow/lawyerRegister/LawyerLoginFrontController.java
- src/com/lawknow/lawyerRegister/LawyerOfficeNameOk.java
> 회원탈퇴 링크 고침

- WebContent/LawKnowMainPage.jsp
- WebContent/findId.jsp
- WebContent/findPw.jsp
- WebContent/find_idpw.jsp
- src/com/lawknow/domain/dao/UserDAO.java
- src/com/lawknow/userRegister/UserFindIdOk.java
- src/com/lawknow/userRegister/UserFindPwOk.java
- src/com/lawknow/userRegister/UserLoginFrontController.java
- src/com/mybatis/mapper/UserMapper.xml
> 아이디 , 비밀번호 찾기

- WebContent/LawKnowMainPage.jsp
- WebContent/LawKnowMainPage2.jsp
- WebContent/login.jsp
- WebContent/logout.jsp
- WebContent/main.jsp
- WebContent/signup.jsp
- src/com/lawknow/lawyerRegister/LawyerJoin.java
- src/com/lawknow/lawyerRegister/LawyerLoginFrontController.java
- src/com/lawknow/userRegister/UserJoin.java
- src/com/lawknow/userRegister/UserLoginFrontController.java
- src/com/lawknow/userRegister/UserLoginOk.java
- src/com/lawknow/userRegister/UserMain.java
> 로그인 오류페이지, 경로수정
